[package]
name = "termwriter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
crossterm = "0.27.0"
lazy_static = "1.5.0"
portable-pty = "0.8.1"
regex = "1.10.5"
